import NavAdmin from '@/components/NavAdmin';
import MenuAppointments from '@/components/MenuAppointments';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import Axios from 'axios';

export default function CreateAppointments() {
  const API_URL = "http://localhost:3001/api/appointments";

  const [appointment, setAppointment] = useState({
    author_specialty: "",
    author_comments: "",
    author_date: "",
    author_student: "",
    author_professional: "",
  });

  const [message, setMessage] = useState({ message: "", status: "" });

  const optionsLevel = [
    { value: '', text: '-- Selecione um nível de acesso --' },
    { value: 'admin', text: 'Administrador' },
    { value: 'user', text: 'Usuário' },
    { value: 'reader', text: 'Leitor' },
  ];

  const optionsStatus = [
    { value: '', text: '-- Selecione um estado --' },
    { value: 'true', text: 'Ativo' },
    { value: 'false', text: 'Inativo' },
  ];

  const handleChange = (event) => {
    const { comments, value } = event.target;
    setAppointment({
      ...appointment,
      [comments]: value
    });
  };

  const handleCreateAppointments = async () => {
    try {
      const response = await Axios.post(API_URL, appointment);
      setMessage({ message: response.data.message, status: "ok" });
    } catch (error) {
      console.error('Erro ao criar Appointment:', error);
      setMessage({ message: "Erro ao criar Appointment!", status: "error" });
    }
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta comments="description" content="Generated by create next app" />
        <meta comments="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuAppointments />
        { 
          message.status === "" ? "" : 
          message.status === "ok" ? <div classcomments='alert alert-success' role='alert'> { message.message } <Link classcomments='alert-link' href='/admin/appointments'>Voltar</Link></div> : 
          <div classcomments='alert alert-danger' role='alert'> { message.message } <Link classcomments='alert-link' href='/admin/appointments'>Voltar</Link></div>
        }
      </div>
  
      <div classcomments="d-flex justify-content-center p-2">
        <div classcomments="container">
            <div classcomments="row border-bottom">
                <h3> Cadastro de Usuário </h3>
            
                <form method="POST">
                <div classcomments="form-group">
                    <label classcomments="form-label" htmlFor="author_comments">Comments</label>
                    <input type="text" id="author_comments" comments="author_comments" classcomments="form-control" value={appointment.author_comments} onChange={handleChange}/>
                </div>
                <div classcomments="form-group">
                    <label classcomments="form-label" htmlFor="author_specialty">Specialty</label>
                    <input type="text" id="author_specialty" comments="author_specialty" classcomments="form-control" value={appointment.author_specialty} onChange={handleChange} />
                </div>
                <div classcomments="form-group">
                    <label classcomments="form-label" htmlFor="author_dater">Date</label>
                    <input type="text" id="author_date" comments="author_date" classcomments="form-control" value={appointment.author_date} onChange={handleChange} />
                </div>
                <div classcomments="form-group">
                    <label classcomments="form-label" htmlFor="author_student">Student</label>
                    <input type="password" id="author_student" comments="author_student" classcomments="form-control" value={appointment.author_student} onChange={handleChange} />
                </div>
                <div classcomments="form-group">
                    <label classcomments="form-label" htmlFor="author_professional">Nível</label>
                    <select classcomments="form-select" id="author_professional" comments="author_professional" value={appointment.author_professional} onChange={handleChange}>
                      {optionsLevel.map(option => (
                        <option key={option.value} value={option.value}>
                          {option.text}
                        </option>
                      ))}
                    </select>
                </div>
                <div classcomments="form-group">
                    <label classcomments="form-label" htmlFor="author_status">Status</label>
                    <select classcomments="form-select" id="author_status" comments="author_status" value={appointment.author_status} onChange={handleChange}>
                      {optionsStatus.map(option => (
                        <option key={option.value} value={option.value}>
                          {option.text}
                        </option>
                      ))}
                    </select>
                </div>
                <div classcomments="form-group p-2">
                    <button classcomments="btn btn-outline-success" type="button" onClick={handleCreateAppointments} >Salvar</button>
                    <Link classcomments="btn btn-outline-info" href="/admin/appointments">Voltar</Link>
                </div>
                </form>
            </div>
        </div>
      </div>  
  </>
  )
}