import { getSession } from 'next-auth/react';
import NavAdmin from '@/components/NavAdmin';
import MenuAdmin from '@/components/MenuAdmin';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import Axios from 'axios';

export default function CreateStudents() {
  const API_URL = "http://localhost:3001/api/students";

  const [students, setStudents] = useState({
    name: "",    // Renomeado para refletir os dados do backend
    age: "",   // Renomeado para refletir os dados do backend
    parents: "",    // Renomeado para refletir os dados do backend
    phone: "",     // Renomeado para refletir os dados do backend
    special: "",   // Renomeado para refletir os dados do backend
    status: "",  // Renomeado para refletir os dados do backend
  });

  const [message, setMessage] = useState({ message: "", status: "" });

  const optionsStatus = [
    { value: '', text: '-- Selecione um estado --' },
    { value: 'true', text: 'Ativo' },
    { value: 'false', text: 'Inativo' },
  ];

  // Função para lidar com as mudanças nos campos do formulário
  const handleChange = (event) => {
    const { name, value } = event.target;
    setStudents({
      ...students,
      [name]: value
    });
  };

  // Função para enviar os dados do formulário e criar um novo usuário
  const handleCreatestudents = async () => {
    try {
      const response = await Axios.post(API_URL, students);  // Envia os dados ao backend
      setMessage({ message: response.data.sucesso, status: "ok" });
    } catch (error) {
      console.error('Erro ao criar o Usuário:', error);
      setMessage({ message: "Erro ao criar o Usuário!", status: "error" });
    }
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuAdmin />
        { 
          message.status === "" ? "" : 
          message.status === "ok" ? <div className='alert alert-success' role='alert'> { message.message } <Link className='alert-link' href='/admin/students'>Voltar</Link></div> : 
          <div className='alert alert-danger' role='alert'> { message.message } <Link className='alert-link' href='/admin/students'>Voltar</Link></div>
        }
      </div>
  
      <div className="d-flex justify-content-center p-2">
        <div className="container">
            <div className="row border-bottom">
                <h3> Cadastro de Usuário </h3>
            
                <form method="POST">
                <div className="form-group">
                    <label className="form-label" htmlFor="name">Nome</label>
                    <input type="text" id="name" name="name" className="form-control" value={students.name} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="age">Idade</label>
                    <input type="number" id="age" name="age" className="form-control" value={students.age} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="parents">Parents</label>
                    <input type="text" id="parents" name="parents" className="form-control" value={students.parents} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="phone">Phone</label>
                    <input type="text" id="phone" name="phone" className="form-control" value={students.phone} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="special">Special</label>
                    <input type="text" id="special" name="special" className="form-control" value={students.special} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="status">Status</label>
                    <select className="form-select" id="status" name="status" value={students.status} onChange={handleChange}>
                      {optionsStatus.map(option => (
                        <option key={option.value} value={option.value}>
                          {option.text}
                        </option>
                      ))}
                    </select>
                </div>
                <div className="form-group p-2">
                    <button className="btn btn-outline-success" type="button" onClick={handleCreatestudents}>Salvar</button>
                    <Link className="btn btn-outline-info" href="/admin/students">Voltar</Link>
                </div>
                </form>
            </div>
        </div>
      </div>  
    </>
  )
}

// Adicionando a verificação de sessão no getServerSideProps
export async function getServerSideProps(context) {
  const session = await getSession({ req: context.req });

  // Verifica se o usuário está logado, caso contrário, redireciona
  if (!session) {
    return {
      redirect: {
        destination: '/login',  // Redireciona para a página de login
        permanent: false,
      },
    };
  }

  // Retorna os dados da página, caso o usuário esteja logado
  return {
    props: { session }, // Passa a sessão como prop
  };
}