import { getSession } from 'next-auth/react';
import NavAdmin from '@/components/NavAdmin';
import MenuAdmin from '@/components/MenuAdmin';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import Axios from 'axios';

export default function CreateStudents() {
  const API_URL = "http://localhost:3001/api/students";

  const [students, setStudents] = useState({
    name: "",   
    age: "",   
    parents: "",   
    phone: "",     
    special: "",   
    status: "",  
  });

  const [message, setMessage] = useState({ message: "", status: "" });

  const optionsStatus = [
    { value: 'true', text: 'Ativo' },
    { value: 'false', text: 'Inativo' },
  ];

 
  const handleChange = (event) => {
    const { name, value } = event.target;
    setStudents({
      ...students,
      [name]: value
    });
  };

  
  const handleCreatestudents = async () => {
    try {
      const response = await Axios.post(API_URL, students); 
      setMessage({ message: response.data.sucesso, status: "ok" });
    } catch (error) {
      console.error('Erro ao criar o Usuário:', error);
      setMessage({ message: "Erro ao criar o Usuário!", status: "error" });
    }
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuAdmin />
      </div>
  
      <div className="d-flex justify-content-center p-2">
        <div className="container">
            <div className="row border-bottom">
            { 
          message.status === "" ? "" : 
          message.status === "ok" ? <div className='alert alert-success' role='alert'> { message.message } <Link className='alert-link' href='/admin/students'>Voltar</Link></div> : 
          <div className='alert alert-danger' role='alert'> { message.message } <Link className='alert-link' href='/admin/students'>Voltar</Link></div>
        }
                <h3> Cadastro de Usuário </h3>
            
                <form method="POST">
                <div className="form-group">
                    <label className="form-label" htmlFor="name">Nome</label>
                    <input type="text" id="name" name="name" className="form-control" value={students.name} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="age">Idade</label>
                    <input type="number" id="age" name="age" className="form-control" value={students.age} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="parents">Responsáveis</label>
                    <input type="text" id="parents" name="parents" className="form-control" value={students.parents} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="phone">Telefone</label>
                    <input type="text" id="phone" name="phone" className="form-control" value={students.phone} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="special">Necessidades Especiais</label>
                    <input type="text" id="special" name="special" className="form-control" value={students.special} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="status">Status</label>
                    <select className="form-select" id="status" name="status" value={students.status} onChange={handleChange}>
                      {optionsStatus.map(option => (
                        <option key={option.value} value={option.value}>
                          {option.text}
                        </option>
                      ))}
                    </select>
                </div>
                <div className="form-group p-2">
                    <button className="btn btn-outline-success" type="button" onClick={handleCreatestudents}>Salvar</button>
                    <Link className="btn btn-outline-info" href="/admin/students">Voltar</Link>
                </div>
                </form>
            </div>
        </div>
      </div>  
    </>
  )
}


export async function getServerSideProps(context) {
  const session = await getSession({ req: context.req });

  
  if (!session) {
    return {
      redirect: {
        destination: '/login',  
        permanent: false,
      },
    };
  }

  
  return {
    props: { session },
  };
}