import NavHome from '@/components/NavHome'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
      <NavHome />
      </div>

      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
              <h3> Sistema de Base de Conhecimentos</h3>
          </div>
        </div>
      </div>  
  </>
  )
}


