import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <>
    <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </Head>
    <div>
    <form action="/admin" method="POST">
    <div className="d-flex justify-content-center p-2">
        <div className="col-md-4">
            <div>
                <h2>Login</h2>
            </div>
            <div className="form-group">
                <label className="form-label" htmlFor="username">Usuário</label>
                <input type="text" id="username" name="username" className="form-control" />
            </div>
            <div className="form-group">
                <label className="form-label" htmlFor="password">Senha</label>  
                <input type="password" id="password" name="password" className="form-control" />
            </div>
            <div className="form-group p-2">
                <button className="btn btn-outline-success"  type="submit" >Login</button>
                <Link className="btn btn-outline-info" href="/">Voltar</Link>
            </div>
        </div>
    </div>
    </form>
    </div>  
  </>
  )
}


