import NavAdmin from '@/components/NavAdmin';
import MenuAdmin from '@/components/MenuAdmin';
import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import Axios from 'axios';

export default function CreateTeacher() {
  const API_URL = "http://localhost:3001/api/teachers";

  const [teacher, setTeacher] = useState({
    name: "",    // Renomeado para refletir os dados do backend
    school_disciplines: "",   // Renomeado para refletir os dados do backend
    contact: "",    // Renomeado para refletir os dados do backend
    phone_number: "",     // Renomeado para refletir os dados do backend
    status: "",  // Renomeado para refletir os dados do backend
  });

  const [message, setMessage] = useState({ message: "", status: "" });

  const optionsStatus = [
    { value: '', text: '-- Selecione um estado --' },
    { value: 'true', text: 'Ativo' },
    { value: 'false', text: 'Inativo' },
  ];

  // Função para lidar com as mudanças nos campos do formulário
  const handleChange = (event) => {
    const { name, value } = event.target;
    setTeacher({
      ...teacher,
      [name]: value
    });
  };

  // Função para enviar os dados do formulário e criar um novo usuário
  const handleCreateTeacher = async () => {
    try {
      const response = await Axios.post(API_URL, teacher);  // Envia os dados ao backend
      setMessage({ message: response.data.sucesso, status: "ok" });
    } catch (error) {
      console.error('Erro ao criar Teacher:', error);
      setMessage({ message: "Erro ao criar Teacher!", status: "error" });
    }
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuAdmin />
        { 
          message.status === "" ? "" : 
          message.status === "ok" ? <div className='alert alert-success' role='alert'> { message.message } <Link className='alert-link' href='/admin/teachers'>Voltar</Link></div> : 
          <div className='alert alert-danger' role='alert'> { message.message } <Link className='alert-link' href='/admin/teachers'>Voltar</Link></div>
        }
      </div>
  
      <div className="d-flex justify-content-center p-2">
        <div className="container">
            <div className="row border-bottom">
                <h3> Cadastro de Professores </h3>
            
                <form method="POST">
                <div className="form-group">
                    <label className="form-label" htmlFor="name">Nome</label>
                    <input type="text" id="name" name="name" className="form-control" value={teacher.name} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="school">Disciplinas</label>
                    <input type="text" id="school" name="school" className="form-control" value={teacher.school_disciplines} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="contact">Contato</label>
                    <input type="text" id="contact" name="contact" className="form-control" value={teacher.contact} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="phone">Número de Telefone</label>
                    <input type="text" id="phone" name="phone" className="form-control" value={teacher.phone_number} onChange={handleChange} />
                </div>
                <div className="form-group">
                    <label className="form-label" htmlFor="status">Status</label>
                    <select className="form-select" id="status" name="status" value={teacher.status} onChange={handleChange}>
                      {optionsStatus.map(option => (
                        <option key={option.value} value={option.value}>
                          {option.text}
                        </option>
                      ))}
                    </select>
                </div>
                <div className="form-group p-2">
                    <button className="btn btn-outline-success" type="button" onClick={handleCreateTeacher}>Salvar</button>
                    <Link className="btn btn-outline-info" href="/admin/teachers">Voltar</Link>
                </div>
                </form>
            </div>
        </div>
      </div>  
    </>
  )
}
