import { getSession } from 'next-auth/react';
import Axios from 'axios'
import NavAdmin from '@/components/NavAdmin'
import MenuAdmin from '@/components/MenuAdmin'
import TeachersAction from '@/components/TeachersAction'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Link from 'next/link'

export default function Teachers() {
  const API_URL = "http://localhost:3001/api/teachers";

  const [teacher, setTeacher] = useState([]);
  const [filteredTeachers, setFilteredTeachers] = useState([]);
  const [search, setSearch] = useState("");

  useEffect(() => {
    const getAllTeachers = async () => {
      try {
        const response = await Axios.get(API_URL);
        setTeacher(response.data);
        setFilteredTeachers(response.data);
      } catch (error) {
        console.error("Erro ao buscar os compromissos:", error);
      }
    };

    getAllTeachers();
  }, []);

  const handleSearch = (e) => {
    const term = e.target.value.toLowerCase();
    setSearch(term);
    const filtered = teacher.filter((teacher) => 
      teacher.name.toLowerCase().includes(term) // Filtro pela data também
    );
    setFilteredTeachers(filtered);
  };

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div>
        <NavAdmin />
        <MenuAdmin />
      </div>

      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
            <h3>Lista de Professores</h3>

            {/* Campo de busca e botão de criar compromisso */}
            <div className="d-flex justify-content-between align-items-center mb-3">
              <input
                type="text"
                placeholder="Buscar por paciente ou data..."
                className="form-control w-50"
                value={search}
                onChange={handleSearch}
              />
              <Link href="/admin/teachers/create" className="btn btn-primary ms-2">
                Criar Professor
              </Link>
            </div>

            {/* Tabela de Compromissos */}
            <table className="table table-hover table-dark">
              <thead>
                <tr>
                  <th scope="col">#</th>
                  <th scope="col">Nome</th>
                  <th scope="col">Disciplina Responsável</th>
                  <th scope="col">Ação</th>
                </tr>
              </thead>
              <tbody>
                {filteredTeachers.map(teacher => (
                  <tr key={teacher._id}>
                    <th scope="row">{teacher._id}</th>
                    <td className="text-truncate">{teacher.name}</td>
                    <td className="text-truncate">{teacher.school_disciplines}</td>
                    <td>
                      <TeachersAction pid={teacher._id} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>

            {filteredTeachers.length === 0 && (
              <p className="text-center text-light">Nenhum compromisso encontrado.</p>
            )}

          </div>
        </div>
      </div>  
    </>
  );
}

// Adicionando a verificação de sessão no getServerSideProps
export async function getServerSideProps(context) {
  const session = await getSession({ req: context.req });

  // Verifica se o usuário está logado, caso contrário, redireciona
  if (!session) {
    return {
      redirect: {
        destination: '/login',  // Redireciona para a página de login
        permanent: false,
      },
    };
  }

  // Retorna os dados da página, caso o usuário esteja logado
  return {
    props: { session }, // Passa a sessão como prop
  };
}
