import MenuAdmin from '@/components/MenuAdmin'
import NavAdmin from '@/components/NavAdmin'
import Head from 'next/head'
import Link from 'next/link'

export default function admin() {
  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuAdmin />
      </div>
  
      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
              <h3> Lista de Contas Atrasadas</h3>
          </div>
          <div className="row border-bottom">
              <h3> Lista de Lancaçamentos</h3>
          </div>
          <div className="row border-bottom">
              <h3> Buscador de Lançamentos</h3>
              <div className="input-group">
                  <input type="text" className="form-control" placeholder="Palavra-chave" aria-describedby="button-busca" />
                  <button className="btn btn-outline-secondary" type="button" id="button-busca">Buscar</button>
              </div>
          </div>
        </div>
      </div>  
  </>
  )
}


