import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import Axios from 'axios';
import NavAdmin from '@/components/NavAdmin';
import MenuAdmin from '@/components/MenuAdmin';
import Head from 'next/head';
import Link from 'next/link';

export default function ReadProfessional() {
  const API_URL = 'http://localhost:3001/api/professionals/'; 

  const [professional, setProfessional] = useState({
    name: '',
    specialty: '',
    contact: '',
    phone_number: '',
    status: '',
  });

  const router = useRouter();
  const { pid } = router.query; 

  const [message, setMessage] = useState({ message: '', status: '' });

  useEffect(() => {
    if (pid) {
      const getProfessional = async () => {
        try {
          const response = await Axios.get(`${API_URL}${pid}`);
          setProfessional(response.data);
        } catch (error) {
          console.error('Erro ao buscar profissional:', error);
          setMessage({ message: 'Erro ao buscar profissional!', status: 'error' });
        }
      };

      getProfessional();
    }
  }, [pid]);

  return (
    <>
      <Head>
        <title>APP-BC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
        <NavAdmin />
        <MenuAdmin />
        {message.status === 'error' && (
          <div className="alert alert-danger" role="alert">
            {message.message} <Link href="/admin/professionals">Voltar</Link>
          </div>
        )}
      </div>
      <div className="d-flex justify-content-center p-2">
        <div className="container">
          <div className="row border-bottom">
            <h3>Detalhes do Profissional</h3>
            <form>
              <div className="form-group">
                <label className="form-label" htmlFor="name">Nome</label>
                <input
                  type="text"
                  id="name"
                  name="name"
                  className="form-control"
                  value={professional.name || ''}
                  readOnly
                />
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="specialty">Especialidade</label>
                <input
                  type="text"
                  id="specialty"
                  name="specialty"
                  className="form-control"
                  value={professional.specialty || ''}
                  readOnly
                />
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="contact">Contato</label>
                <input
                  type="text"
                  id="contact"
                  name="contact"
                  className="form-control"
                  value={professional.contact || ''}
                  readOnly
                />
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="phone_number">Número de Telefone</label>
                <input
                  type="text"
                  id="phone_number"
                  name="phone_number"
                  className="form-control"
                  value={professional.phone_number || ''}
                  readOnly
                />
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="status">Status</label>
                <input
                  type="text"
                  id="status"
                  name="status"
                  className="form-control"
                  value={professional.status === 'true' ? 'Ativo' : 'Inativo'}
                  readOnly
                />
              </div>
              <div className="form-group p-2">
                <Link className="btn btn-outline-info" href="/admin/professionals">
                  Voltar
                </Link>
              </div>
            </form>
          </div>
        </div>
      </div>
    </>
  );
}
